### ISSUE TITLE
[DRC-479] [Bug] `--target` does not work in review mode

### ISSUE THREAD

**Issue by yoshi40** [DataRecce/recce#332]
### Current Behavior

When I run the `recce server` command with review mode option and target option (like the below example), The target option is ignored and `recce server` command is executed with the default profile not with the specified profile (not with prod profile in the below example).

```console
recce server --target prod --review recce-state.json
```

### Expected Behavior

`recce server` command will be executed with the specified profile.

(I have also confirmed that target option worked **without** review mode)

### Steps To Reproduce

1. Follow the [5 Minutes Tutorial](https://datarecce.io/docs/get-started-jaffle-shop/) except the setting of profiles.yml: add the additional configuration on the log output like following

  ```yml
  jaffle_shop:
    target: dev
    outputs:
      dev:
        type: duckdb
        path: 'jaffle_shop.duckdb'
        threads: 24
        settings:
          log_query_path: dev.log
      prod:
        type: duckdb
        path: 'jaffle_shop.duckdb'
        schema: prod
        threads: 24
        settings:
          log_query_path: prod.log
  ```

2. run `rm dev.log prod.log` to remove the logs generated by `dbt seed` and `dbt run` command 
3. run `recce server`
  a. In the Query page in the WebUI, run the query: `select 'Hello from default'` (not run diff)
4. run `recce server --target prod`
  a. In the Query page in the WebUI, run the query: `select 'Hello from prod'`
  b. Export the state file for the next step (the name of the state file: `recce-state-2024-06-03-11-01-06.json`)
5. Confirm that without review mode there is no problem (the output of log files are like followings) and run `rm dev.log prod.log`
  - `dev.log`
    ```log
    BEGIN
    select 'Hello from default'
    ```
  - `prod.log`
    ```log
    BEGIN
    select 'Hello from prod'
    ```

6. run `recce server --review recce-state-2024-06-03-11-01-06.json`
  - In the Query page in the WebUI, run the query: `select 'Hello from default review'`
7. run `recce server --target prod --review recce-state-2024-06-03-11-01-06.json`
  - In the Query page in the WebUI, run the query: `select 'Hello from prod review'`
8. check that the log file `prod.log` is not generated and the content of the log file `dev.log` is like following. (I think that the the command is executed with the default profile)
  ```log
  BEGIN
  select 'Hello from prod review'
  w'
  ```
 

### Environment

- recce: 0.20.0
- OS: macOS 14.3.1
- Python: 3.11.2
- Data Warehouse: DuckDB (Also Snowflake)
- dbt: dbt-core: 1.7.9, dbt-duckdb: 1.7.3 (dbt-core: 1.81, dbt-snowflake: 1.8.2 in Snowflake)

### Additional Context

I have found this problem with Snowflake adapter for the first time. However I have reported the issue with DuckDB because it is difficult to explain the steps to reproduce the problem with Snowflake.

I am not a English native, so I apologize for unnatural English if exists. 

<sub>[DRC-479](https://linear.app/piperider/issue/DRC-479/[bug]-target-does-not-work-in-review-mode)</sub>
