### ISSUE TITLE
[Bug] Lineage UI not showing up

### ISSUE THREAD

**Issue by alexeyegorov** [DataRecce/recce#722]
### Current Behavior

Recce lineage is not showing up.

<img width="1523" alt="Image" src="https://github.com/user-attachments/assets/2b6a5b9d-6da9-475c-a4ac-98d1d6d67766" />

<img width="936" alt="Image" src="https://github.com/user-attachments/assets/554e0124-059b-4e85-97b8-1ef77a3c1e36" />

### Expected Behavior

Lineage UI should be presented.

### Steps To Reproduce

This behavior happens randomly (as it seems so far). Lineage shows up in some PRs and disappears in others. 

### Relevant log output

```shell

```

### Environment

1. Running the setup in a devcontainer based on `mcr.microsoft.com/vscode/devcontainers/python:3.11`
1. DBT Packages installed:
    ```
    packages:
      - package: dbt-labs/dbt_utils
        version: 1.3.0
      - package: metaplane/dbt_expectations
        version: 0.10.8
      - package: dbt-labs/audit_helper
        version: 0.12.1
      - package: data-mie/dbt_profiler
        version: 0.8.4
    ```
2. Python version: 3.11
3. Python requirements:    
    ```
    dbt-databricks==1.9.7
    pre-commit==4.2.0
    recce==1.0.1
    sqlfluff==3.3.1
    sqlfluff-templater-dbt==3.3.1
    ```
